# Generated by Django 4.2.13 on 2024-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('date_of_birth', models.EmailField(max_length=254)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.PositiveSmallIntegerField()),
                ('experience', models.PositiveSmallIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('level_of_studies', models.CharField(max_length=20)),
            ],
        ),
    ]
