# Generated by Django 4.2.13 on 2024-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cources_name', models.CharField(max_length=20)),
                ('course_number', models.PositiveSmallIntegerField()),
                ('course_teacher', models.CharField(max_length=20)),
                ('course_details', models.CharField(max_length=20)),
                ('course_schedule', models.CharField(max_length=20)),
                ('course_break', models.CharField(max_length=20)),
                ('course_intrest', models.CharField(max_length=20)),
                ('course_requirnment', models.CharField(max_length=20)),
                ('course_id', models.PositiveSmallIntegerField()),
                ('course_points', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
